server:
  port: 1000
spring:
  application:
    name: config-server
  profiles:
    active: native
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
